// Generated by gencpp from file boustrophedon_msgs/ConvertPlanToPath.msg
// DO NOT EDIT!


#ifndef BOUSTROPHEDON_MSGS_MESSAGE_CONVERTPLANTOPATH_H
#define BOUSTROPHEDON_MSGS_MESSAGE_CONVERTPLANTOPATH_H

#include <ros/service_traits.h>


#include <boustrophedon_msgs/ConvertPlanToPathRequest.h>
#include <boustrophedon_msgs/ConvertPlanToPathResponse.h>


namespace boustrophedon_msgs
{

struct ConvertPlanToPath
{

typedef ConvertPlanToPathRequest Request;
typedef ConvertPlanToPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConvertPlanToPath
} // namespace boustrophedon_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::boustrophedon_msgs::ConvertPlanToPath > {
  static const char* value()
  {
    return "3a9fa9a5fc158705104b513251035497";
  }

  static const char* value(const ::boustrophedon_msgs::ConvertPlanToPath&) { return value(); }
};

template<>
struct DataType< ::boustrophedon_msgs::ConvertPlanToPath > {
  static const char* value()
  {
    return "boustrophedon_msgs/ConvertPlanToPath";
  }

  static const char* value(const ::boustrophedon_msgs::ConvertPlanToPath&) { return value(); }
};


// service_traits::MD5Sum< ::boustrophedon_msgs::ConvertPlanToPathRequest> should match
// service_traits::MD5Sum< ::boustrophedon_msgs::ConvertPlanToPath >
template<>
struct MD5Sum< ::boustrophedon_msgs::ConvertPlanToPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::boustrophedon_msgs::ConvertPlanToPath >::value();
  }
  static const char* value(const ::boustrophedon_msgs::ConvertPlanToPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::boustrophedon_msgs::ConvertPlanToPathRequest> should match
// service_traits::DataType< ::boustrophedon_msgs::ConvertPlanToPath >
template<>
struct DataType< ::boustrophedon_msgs::ConvertPlanToPathRequest>
{
  static const char* value()
  {
    return DataType< ::boustrophedon_msgs::ConvertPlanToPath >::value();
  }
  static const char* value(const ::boustrophedon_msgs::ConvertPlanToPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::boustrophedon_msgs::ConvertPlanToPathResponse> should match
// service_traits::MD5Sum< ::boustrophedon_msgs::ConvertPlanToPath >
template<>
struct MD5Sum< ::boustrophedon_msgs::ConvertPlanToPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::boustrophedon_msgs::ConvertPlanToPath >::value();
  }
  static const char* value(const ::boustrophedon_msgs::ConvertPlanToPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::boustrophedon_msgs::ConvertPlanToPathResponse> should match
// service_traits::DataType< ::boustrophedon_msgs::ConvertPlanToPath >
template<>
struct DataType< ::boustrophedon_msgs::ConvertPlanToPathResponse>
{
  static const char* value()
  {
    return DataType< ::boustrophedon_msgs::ConvertPlanToPath >::value();
  }
  static const char* value(const ::boustrophedon_msgs::ConvertPlanToPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOUSTROPHEDON_MSGS_MESSAGE_CONVERTPLANTOPATH_H
