// Generated by gencpp from file boustrophedon_msgs/ConvertPlanToPathRequest.msg
// DO NOT EDIT!


#ifndef BOUSTROPHEDON_MSGS_MESSAGE_CONVERTPLANTOPATHREQUEST_H
#define BOUSTROPHEDON_MSGS_MESSAGE_CONVERTPLANTOPATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <boustrophedon_msgs/StripingPlan.h>

namespace boustrophedon_msgs
{
template <class ContainerAllocator>
struct ConvertPlanToPathRequest_
{
  typedef ConvertPlanToPathRequest_<ContainerAllocator> Type;

  ConvertPlanToPathRequest_()
    : plan()  {
    }
  ConvertPlanToPathRequest_(const ContainerAllocator& _alloc)
    : plan(_alloc)  {
  (void)_alloc;
    }



   typedef  ::boustrophedon_msgs::StripingPlan_<ContainerAllocator>  _plan_type;
  _plan_type plan;





  typedef boost::shared_ptr< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConvertPlanToPathRequest_

typedef ::boustrophedon_msgs::ConvertPlanToPathRequest_<std::allocator<void> > ConvertPlanToPathRequest;

typedef boost::shared_ptr< ::boustrophedon_msgs::ConvertPlanToPathRequest > ConvertPlanToPathRequestPtr;
typedef boost::shared_ptr< ::boustrophedon_msgs::ConvertPlanToPathRequest const> ConvertPlanToPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator1> & lhs, const ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.plan == rhs.plan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator1> & lhs, const ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace boustrophedon_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7a5dc2a7fd3a005db67fe266f849039";
  }

  static const char* value(const ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7a5dc2a7fd3a005ULL;
  static const uint64_t static_value2 = 0xdb67fe266f849039ULL;
};

template<class ContainerAllocator>
struct DataType< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "boustrophedon_msgs/ConvertPlanToPathRequest";
  }

  static const char* value(const ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "boustrophedon_msgs/StripingPlan plan\n"
"\n"
"================================================================================\n"
"MSG: boustrophedon_msgs/StripingPlan\n"
"Header header\n"
"StripingPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: boustrophedon_msgs/StripingPoint\n"
"geometry_msgs/Point point\n"
"uint8 type\n"
"\n"
"uint8 OUTLINE = 0\n"
"uint8 STRIPE_START = 1\n"
"uint8 STRIPE_END = 2\n"
"uint8 STRIPE_INTERMEDIATE = 3\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConvertPlanToPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::boustrophedon_msgs::ConvertPlanToPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "plan: ";
    s << std::endl;
    Printer< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >::stream(s, indent + "  ", v.plan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOUSTROPHEDON_MSGS_MESSAGE_CONVERTPLANTOPATHREQUEST_H
