// Generated by gencpp from file boustrophedon_msgs/PlanMowingPathGoal.msg
// DO NOT EDIT!


#ifndef BOUSTROPHEDON_MSGS_MESSAGE_PLANMOWINGPATHGOAL_H
#define BOUSTROPHEDON_MSGS_MESSAGE_PLANMOWINGPATHGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PolygonStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace boustrophedon_msgs
{
template <class ContainerAllocator>
struct PlanMowingPathGoal_
{
  typedef PlanMowingPathGoal_<ContainerAllocator> Type;

  PlanMowingPathGoal_()
    : property()
    , robot_position()  {
    }
  PlanMowingPathGoal_(const ContainerAllocator& _alloc)
    : property(_alloc)
    , robot_position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PolygonStamped_<ContainerAllocator>  _property_type;
  _property_type property;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _robot_position_type;
  _robot_position_type robot_position;





  typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PlanMowingPathGoal_

typedef ::boustrophedon_msgs::PlanMowingPathGoal_<std::allocator<void> > PlanMowingPathGoal;

typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathGoal > PlanMowingPathGoalPtr;
typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathGoal const> PlanMowingPathGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator1> & lhs, const ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator2> & rhs)
{
  return lhs.property == rhs.property &&
    lhs.robot_position == rhs.robot_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator1> & lhs, const ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace boustrophedon_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60b9ea9efd7a7b3f7b33904f663aa7de";
  }

  static const char* value(const ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60b9ea9efd7a7b3fULL;
  static const uint64_t static_value2 = 0x7b33904f663aa7deULL;
};

template<class ContainerAllocator>
struct DataType< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "boustrophedon_msgs/PlanMowingPathGoal";
  }

  static const char* value(const ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/PolygonStamped property\n"
"geometry_msgs/PoseStamped robot_position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.property);
      stream.next(m.robot_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanMowingPathGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator>& v)
  {
    s << indent << "property: ";
    s << std::endl;
    Printer< ::geometry_msgs::PolygonStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.property);
    s << indent << "robot_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOUSTROPHEDON_MSGS_MESSAGE_PLANMOWINGPATHGOAL_H
