// Generated by gencpp from file boustrophedon_msgs/PlanMowingPathActionGoal.msg
// DO NOT EDIT!


#ifndef BOUSTROPHEDON_MSGS_MESSAGE_PLANMOWINGPATHACTIONGOAL_H
#define BOUSTROPHEDON_MSGS_MESSAGE_PLANMOWINGPATHACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <boustrophedon_msgs/PlanMowingPathGoal.h>

namespace boustrophedon_msgs
{
template <class ContainerAllocator>
struct PlanMowingPathActionGoal_
{
  typedef PlanMowingPathActionGoal_<ContainerAllocator> Type;

  PlanMowingPathActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  PlanMowingPathActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PlanMowingPathActionGoal_

typedef ::boustrophedon_msgs::PlanMowingPathActionGoal_<std::allocator<void> > PlanMowingPathActionGoal;

typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathActionGoal > PlanMowingPathActionGoalPtr;
typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathActionGoal const> PlanMowingPathActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator1> & lhs, const ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator1> & lhs, const ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace boustrophedon_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ea4cac64234a3e0b5c932e94dddf036";
  }

  static const char* value(const ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ea4cac64234a3e0ULL;
  static const uint64_t static_value2 = 0xb5c932e94dddf036ULL;
};

template<class ContainerAllocator>
struct DataType< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "boustrophedon_msgs/PlanMowingPathActionGoal";
  }

  static const char* value(const ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"PlanMowingPathGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: boustrophedon_msgs/PlanMowingPathGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/PolygonStamped property\n"
"geometry_msgs/PoseStamped robot_position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PolygonStamped\n"
"# This represents a Polygon with reference coordinate frame and timestamp\n"
"Header header\n"
"Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanMowingPathActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::boustrophedon_msgs::PlanMowingPathActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::boustrophedon_msgs::PlanMowingPathGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOUSTROPHEDON_MSGS_MESSAGE_PLANMOWINGPATHACTIONGOAL_H
