// Generated by gencpp from file boustrophedon_msgs/PlanMowingPathFeedback.msg
// DO NOT EDIT!


#ifndef BOUSTROPHEDON_MSGS_MESSAGE_PLANMOWINGPATHFEEDBACK_H
#define BOUSTROPHEDON_MSGS_MESSAGE_PLANMOWINGPATHFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace boustrophedon_msgs
{
template <class ContainerAllocator>
struct PlanMowingPathFeedback_
{
  typedef PlanMowingPathFeedback_<ContainerAllocator> Type;

  PlanMowingPathFeedback_()
    {
    }
  PlanMowingPathFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PlanMowingPathFeedback_

typedef ::boustrophedon_msgs::PlanMowingPathFeedback_<std::allocator<void> > PlanMowingPathFeedback;

typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathFeedback > PlanMowingPathFeedbackPtr;
typedef boost::shared_ptr< ::boustrophedon_msgs::PlanMowingPathFeedback const> PlanMowingPathFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace boustrophedon_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "boustrophedon_msgs/PlanMowingPathFeedback";
  }

  static const char* value(const ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
;
  }

  static const char* value(const ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanMowingPathFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::boustrophedon_msgs::PlanMowingPathFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BOUSTROPHEDON_MSGS_MESSAGE_PLANMOWINGPATHFEEDBACK_H
