// Generated by gencpp from file boustrophedon_msgs/StripingPlan.msg
// DO NOT EDIT!


#ifndef BOUSTROPHEDON_MSGS_MESSAGE_STRIPINGPLAN_H
#define BOUSTROPHEDON_MSGS_MESSAGE_STRIPINGPLAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <boustrophedon_msgs/StripingPoint.h>

namespace boustrophedon_msgs
{
template <class ContainerAllocator>
struct StripingPlan_
{
  typedef StripingPlan_<ContainerAllocator> Type;

  StripingPlan_()
    : header()
    , points()  {
    }
  StripingPlan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::boustrophedon_msgs::StripingPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::boustrophedon_msgs::StripingPoint_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> const> ConstPtr;

}; // struct StripingPlan_

typedef ::boustrophedon_msgs::StripingPlan_<std::allocator<void> > StripingPlan;

typedef boost::shared_ptr< ::boustrophedon_msgs::StripingPlan > StripingPlanPtr;
typedef boost::shared_ptr< ::boustrophedon_msgs::StripingPlan const> StripingPlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::boustrophedon_msgs::StripingPlan_<ContainerAllocator1> & lhs, const ::boustrophedon_msgs::StripingPlan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::boustrophedon_msgs::StripingPlan_<ContainerAllocator1> & lhs, const ::boustrophedon_msgs::StripingPlan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace boustrophedon_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2838ae4f42498e5013db14343fd340a";
  }

  static const char* value(const ::boustrophedon_msgs::StripingPlan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2838ae4f42498e5ULL;
  static const uint64_t static_value2 = 0x013db14343fd340aULL;
};

template<class ContainerAllocator>
struct DataType< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "boustrophedon_msgs/StripingPlan";
  }

  static const char* value(const ::boustrophedon_msgs::StripingPlan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"StripingPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: boustrophedon_msgs/StripingPoint\n"
"geometry_msgs/Point point\n"
"uint8 type\n"
"\n"
"uint8 OUTLINE = 0\n"
"uint8 STRIPE_START = 1\n"
"uint8 STRIPE_END = 2\n"
"uint8 STRIPE_INTERMEDIATE = 3\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::boustrophedon_msgs::StripingPlan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StripingPlan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::boustrophedon_msgs::StripingPlan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::boustrophedon_msgs::StripingPlan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::boustrophedon_msgs::StripingPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOUSTROPHEDON_MSGS_MESSAGE_STRIPINGPLAN_H
