(cl:defpackage boustrophedon_msgs-msg
  (:use )
  (:export
   "<PLANMOWINGPATHACTION>"
   "PLANMOWINGPATHACTION"
   "<PLANMOWINGPATHACTIONFEEDBACK>"
   "PLANMOWINGPATHACTIONFEEDBACK"
   "<PLANMOWINGPATHACTIONGOAL>"
   "PLANMOWINGPATHACTIONGOAL"
   "<PLANMOWINGPATHACTIONRESULT>"
   "PLANMOWINGPATHACTIONRESULT"
   "<PLANMOWINGPATHFEEDBACK>"
   "PLANMOWINGPATHFEEDBACK"
   "<PLANMOWINGPATHGOAL>"
   "PLANMOWINGPATHGOAL"
   "<PLANMOWINGPATHRESULT>"
   "PLANMOWINGPATHRESULT"
   "<STRIPINGPLAN>"
   "STRIPINGPLAN"
   "<STRIPINGPOINT>"
   "STRIPINGPOINT"
  ))

