; Auto-generated. Do not edit!


(cl:in-package boustrophedon_msgs-msg)


;//! \htmlinclude PlanMowingPathFeedback.msg.html

(cl:defclass <PlanMowingPathFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlanMowingPathFeedback (<PlanMowingPathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlanMowingPathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlanMowingPathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name boustrophedon_msgs-msg:<PlanMowingPathFeedback> is deprecated: use boustrophedon_msgs-msg:PlanMowingPathFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlanMowingPathFeedback>) ostream)
  "Serializes a message object of type '<PlanMowingPathFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlanMowingPathFeedback>) istream)
  "Deserializes a message object of type '<PlanMowingPathFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlanMowingPathFeedback>)))
  "Returns string type for a message object of type '<PlanMowingPathFeedback>"
  "boustrophedon_msgs/PlanMowingPathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlanMowingPathFeedback)))
  "Returns string type for a message object of type 'PlanMowingPathFeedback"
  "boustrophedon_msgs/PlanMowingPathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlanMowingPathFeedback>)))
  "Returns md5sum for a message object of type '<PlanMowingPathFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlanMowingPathFeedback)))
  "Returns md5sum for a message object of type 'PlanMowingPathFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlanMowingPathFeedback>)))
  "Returns full string definition for message of type '<PlanMowingPathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlanMowingPathFeedback)))
  "Returns full string definition for message of type 'PlanMowingPathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlanMowingPathFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlanMowingPathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlanMowingPathFeedback
))
